name: Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Build documentation
      run: cargo doc --no-deps --all-features
    - name: Check documentation links
      run: cargo doc --no-deps --all-features
      env:
        RUSTDOCFLAGS: "-D warnings"